# Duration: How long the potion effect will last for. This will take some editing per the height of your spawn. #
# Amp: What amplifier should we use? 1 brings them up slow, 50 throws em back up! #
# yHeight: At which height should we activate the levitation? (0 = void) #

duration: 35
amp: 50
yheight: 0